#!/usr/bin/env python
import sys, json
content = json.load(sys.stdin)

for obj in content:
    try:
        parent = obj['parent']
    except KeyError:
        continue
    if type(parent) is str:
        parent = [parent]
    for p in parent:
        print(p, "->", obj['id'], ";")
